// Code generated by protoc-gen-go.
// source: Master.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GetProcedureResultResponse_State int32

const (
	GetProcedureResultResponse_NOT_FOUND GetProcedureResultResponse_State = 0
	GetProcedureResultResponse_RUNNING   GetProcedureResultResponse_State = 1
	GetProcedureResultResponse_FINISHED  GetProcedureResultResponse_State = 2
)

var GetProcedureResultResponse_State_name = map[int32]string{
	0: "NOT_FOUND",
	1: "RUNNING",
	2: "FINISHED",
}
var GetProcedureResultResponse_State_value = map[string]int32{
	"NOT_FOUND": 0,
	"RUNNING":   1,
	"FINISHED":  2,
}

func (x GetProcedureResultResponse_State) Enum() *GetProcedureResultResponse_State {
	p := new(GetProcedureResultResponse_State)
	*p = x
	return p
}
func (x GetProcedureResultResponse_State) String() string {
	return proto.EnumName(GetProcedureResultResponse_State_name, int32(x))
}
func (x *GetProcedureResultResponse_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetProcedureResultResponse_State_value, data, "GetProcedureResultResponse_State")
	if err != nil {
		return err
	}
	*x = GetProcedureResultResponse_State(value)
	return nil
}

type AddColumnRequest struct {
	TableName        *TableName          `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	ColumnFamilies   *ColumnFamilySchema `protobuf:"bytes,2,req,name=column_families" json:"column_families,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *AddColumnRequest) Reset()         { *m = AddColumnRequest{} }
func (m *AddColumnRequest) String() string { return proto.CompactTextString(m) }
func (*AddColumnRequest) ProtoMessage()    {}

func (m *AddColumnRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *AddColumnRequest) GetColumnFamilies() *ColumnFamilySchema {
	if m != nil {
		return m.ColumnFamilies
	}
	return nil
}

type AddColumnResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AddColumnResponse) Reset()         { *m = AddColumnResponse{} }
func (m *AddColumnResponse) String() string { return proto.CompactTextString(m) }
func (*AddColumnResponse) ProtoMessage()    {}

type DeleteColumnRequest struct {
	TableName        *TableName `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	ColumnName       []byte     `protobuf:"bytes,2,req,name=column_name" json:"column_name,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *DeleteColumnRequest) Reset()         { *m = DeleteColumnRequest{} }
func (m *DeleteColumnRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteColumnRequest) ProtoMessage()    {}

func (m *DeleteColumnRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *DeleteColumnRequest) GetColumnName() []byte {
	if m != nil {
		return m.ColumnName
	}
	return nil
}

type DeleteColumnResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteColumnResponse) Reset()         { *m = DeleteColumnResponse{} }
func (m *DeleteColumnResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteColumnResponse) ProtoMessage()    {}

type ModifyColumnRequest struct {
	TableName        *TableName          `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	ColumnFamilies   *ColumnFamilySchema `protobuf:"bytes,2,req,name=column_families" json:"column_families,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ModifyColumnRequest) Reset()         { *m = ModifyColumnRequest{} }
func (m *ModifyColumnRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyColumnRequest) ProtoMessage()    {}

func (m *ModifyColumnRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *ModifyColumnRequest) GetColumnFamilies() *ColumnFamilySchema {
	if m != nil {
		return m.ColumnFamilies
	}
	return nil
}

type ModifyColumnResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ModifyColumnResponse) Reset()         { *m = ModifyColumnResponse{} }
func (m *ModifyColumnResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyColumnResponse) ProtoMessage()    {}

type MoveRegionRequest struct {
	Region           *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	DestServerName   *ServerName      `protobuf:"bytes,2,opt,name=dest_server_name" json:"dest_server_name,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MoveRegionRequest) Reset()         { *m = MoveRegionRequest{} }
func (m *MoveRegionRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRegionRequest) ProtoMessage()    {}

func (m *MoveRegionRequest) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *MoveRegionRequest) GetDestServerName() *ServerName {
	if m != nil {
		return m.DestServerName
	}
	return nil
}

type MoveRegionResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MoveRegionResponse) Reset()         { *m = MoveRegionResponse{} }
func (m *MoveRegionResponse) String() string { return proto.CompactTextString(m) }
func (*MoveRegionResponse) ProtoMessage()    {}

// *
// Dispatch merging the specified regions.
type DispatchMergingRegionsRequest struct {
	RegionA          *RegionSpecifier `protobuf:"bytes,1,req,name=region_a" json:"region_a,omitempty"`
	RegionB          *RegionSpecifier `protobuf:"bytes,2,req,name=region_b" json:"region_b,omitempty"`
	Forcible         *bool            `protobuf:"varint,3,opt,name=forcible,def=0" json:"forcible,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *DispatchMergingRegionsRequest) Reset()         { *m = DispatchMergingRegionsRequest{} }
func (m *DispatchMergingRegionsRequest) String() string { return proto.CompactTextString(m) }
func (*DispatchMergingRegionsRequest) ProtoMessage()    {}

const Default_DispatchMergingRegionsRequest_Forcible bool = false

func (m *DispatchMergingRegionsRequest) GetRegionA() *RegionSpecifier {
	if m != nil {
		return m.RegionA
	}
	return nil
}

func (m *DispatchMergingRegionsRequest) GetRegionB() *RegionSpecifier {
	if m != nil {
		return m.RegionB
	}
	return nil
}

func (m *DispatchMergingRegionsRequest) GetForcible() bool {
	if m != nil && m.Forcible != nil {
		return *m.Forcible
	}
	return Default_DispatchMergingRegionsRequest_Forcible
}

type DispatchMergingRegionsResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DispatchMergingRegionsResponse) Reset()         { *m = DispatchMergingRegionsResponse{} }
func (m *DispatchMergingRegionsResponse) String() string { return proto.CompactTextString(m) }
func (*DispatchMergingRegionsResponse) ProtoMessage()    {}

type AssignRegionRequest struct {
	Region           *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *AssignRegionRequest) Reset()         { *m = AssignRegionRequest{} }
func (m *AssignRegionRequest) String() string { return proto.CompactTextString(m) }
func (*AssignRegionRequest) ProtoMessage()    {}

func (m *AssignRegionRequest) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

type AssignRegionResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AssignRegionResponse) Reset()         { *m = AssignRegionResponse{} }
func (m *AssignRegionResponse) String() string { return proto.CompactTextString(m) }
func (*AssignRegionResponse) ProtoMessage()    {}

type UnassignRegionRequest struct {
	Region           *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	Force            *bool            `protobuf:"varint,2,opt,name=force,def=0" json:"force,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *UnassignRegionRequest) Reset()         { *m = UnassignRegionRequest{} }
func (m *UnassignRegionRequest) String() string { return proto.CompactTextString(m) }
func (*UnassignRegionRequest) ProtoMessage()    {}

const Default_UnassignRegionRequest_Force bool = false

func (m *UnassignRegionRequest) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *UnassignRegionRequest) GetForce() bool {
	if m != nil && m.Force != nil {
		return *m.Force
	}
	return Default_UnassignRegionRequest_Force
}

type UnassignRegionResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnassignRegionResponse) Reset()         { *m = UnassignRegionResponse{} }
func (m *UnassignRegionResponse) String() string { return proto.CompactTextString(m) }
func (*UnassignRegionResponse) ProtoMessage()    {}

type OfflineRegionRequest struct {
	Region           *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *OfflineRegionRequest) Reset()         { *m = OfflineRegionRequest{} }
func (m *OfflineRegionRequest) String() string { return proto.CompactTextString(m) }
func (*OfflineRegionRequest) ProtoMessage()    {}

func (m *OfflineRegionRequest) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

type OfflineRegionResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *OfflineRegionResponse) Reset()         { *m = OfflineRegionResponse{} }
func (m *OfflineRegionResponse) String() string { return proto.CompactTextString(m) }
func (*OfflineRegionResponse) ProtoMessage()    {}

type CreateTableRequest struct {
	TableSchema      *TableSchema `protobuf:"bytes,1,req,name=table_schema" json:"table_schema,omitempty"`
	SplitKeys        [][]byte     `protobuf:"bytes,2,rep,name=split_keys" json:"split_keys,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CreateTableRequest) Reset()         { *m = CreateTableRequest{} }
func (m *CreateTableRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTableRequest) ProtoMessage()    {}

func (m *CreateTableRequest) GetTableSchema() *TableSchema {
	if m != nil {
		return m.TableSchema
	}
	return nil
}

func (m *CreateTableRequest) GetSplitKeys() [][]byte {
	if m != nil {
		return m.SplitKeys
	}
	return nil
}

type CreateTableResponse struct {
	ProcId           *uint64 `protobuf:"varint,1,opt,name=proc_id" json:"proc_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateTableResponse) Reset()         { *m = CreateTableResponse{} }
func (m *CreateTableResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTableResponse) ProtoMessage()    {}

func (m *CreateTableResponse) GetProcId() uint64 {
	if m != nil && m.ProcId != nil {
		return *m.ProcId
	}
	return 0
}

type DeleteTableRequest struct {
	TableName        *TableName `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *DeleteTableRequest) Reset()         { *m = DeleteTableRequest{} }
func (m *DeleteTableRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTableRequest) ProtoMessage()    {}

func (m *DeleteTableRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

type DeleteTableResponse struct {
	ProcId           *uint64 `protobuf:"varint,1,opt,name=proc_id" json:"proc_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteTableResponse) Reset()         { *m = DeleteTableResponse{} }
func (m *DeleteTableResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTableResponse) ProtoMessage()    {}

func (m *DeleteTableResponse) GetProcId() uint64 {
	if m != nil && m.ProcId != nil {
		return *m.ProcId
	}
	return 0
}

type TruncateTableRequest struct {
	TableName        *TableName `protobuf:"bytes,1,req,name=tableName" json:"tableName,omitempty"`
	PreserveSplits   *bool      `protobuf:"varint,2,opt,name=preserveSplits,def=0" json:"preserveSplits,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *TruncateTableRequest) Reset()         { *m = TruncateTableRequest{} }
func (m *TruncateTableRequest) String() string { return proto.CompactTextString(m) }
func (*TruncateTableRequest) ProtoMessage()    {}

const Default_TruncateTableRequest_PreserveSplits bool = false

func (m *TruncateTableRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *TruncateTableRequest) GetPreserveSplits() bool {
	if m != nil && m.PreserveSplits != nil {
		return *m.PreserveSplits
	}
	return Default_TruncateTableRequest_PreserveSplits
}

type TruncateTableResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *TruncateTableResponse) Reset()         { *m = TruncateTableResponse{} }
func (m *TruncateTableResponse) String() string { return proto.CompactTextString(m) }
func (*TruncateTableResponse) ProtoMessage()    {}

type EnableTableRequest struct {
	TableName        *TableName `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *EnableTableRequest) Reset()         { *m = EnableTableRequest{} }
func (m *EnableTableRequest) String() string { return proto.CompactTextString(m) }
func (*EnableTableRequest) ProtoMessage()    {}

func (m *EnableTableRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

type EnableTableResponse struct {
	ProcId           *uint64 `protobuf:"varint,1,opt,name=proc_id" json:"proc_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnableTableResponse) Reset()         { *m = EnableTableResponse{} }
func (m *EnableTableResponse) String() string { return proto.CompactTextString(m) }
func (*EnableTableResponse) ProtoMessage()    {}

func (m *EnableTableResponse) GetProcId() uint64 {
	if m != nil && m.ProcId != nil {
		return *m.ProcId
	}
	return 0
}

type DisableTableRequest struct {
	TableName        *TableName `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *DisableTableRequest) Reset()         { *m = DisableTableRequest{} }
func (m *DisableTableRequest) String() string { return proto.CompactTextString(m) }
func (*DisableTableRequest) ProtoMessage()    {}

func (m *DisableTableRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

type DisableTableResponse struct {
	ProcId           *uint64 `protobuf:"varint,1,opt,name=proc_id" json:"proc_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DisableTableResponse) Reset()         { *m = DisableTableResponse{} }
func (m *DisableTableResponse) String() string { return proto.CompactTextString(m) }
func (*DisableTableResponse) ProtoMessage()    {}

func (m *DisableTableResponse) GetProcId() uint64 {
	if m != nil && m.ProcId != nil {
		return *m.ProcId
	}
	return 0
}

type ModifyTableRequest struct {
	TableName        *TableName   `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	TableSchema      *TableSchema `protobuf:"bytes,2,req,name=table_schema" json:"table_schema,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ModifyTableRequest) Reset()         { *m = ModifyTableRequest{} }
func (m *ModifyTableRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyTableRequest) ProtoMessage()    {}

func (m *ModifyTableRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *ModifyTableRequest) GetTableSchema() *TableSchema {
	if m != nil {
		return m.TableSchema
	}
	return nil
}

type ModifyTableResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ModifyTableResponse) Reset()         { *m = ModifyTableResponse{} }
func (m *ModifyTableResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyTableResponse) ProtoMessage()    {}

type CreateNamespaceRequest struct {
	NamespaceDescriptor *NamespaceDescriptor `protobuf:"bytes,1,req,name=namespaceDescriptor" json:"namespaceDescriptor,omitempty"`
	XXX_unrecognized    []byte               `json:"-"`
}

func (m *CreateNamespaceRequest) Reset()         { *m = CreateNamespaceRequest{} }
func (m *CreateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRequest) ProtoMessage()    {}

func (m *CreateNamespaceRequest) GetNamespaceDescriptor() *NamespaceDescriptor {
	if m != nil {
		return m.NamespaceDescriptor
	}
	return nil
}

type CreateNamespaceResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateNamespaceResponse) Reset()         { *m = CreateNamespaceResponse{} }
func (m *CreateNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceResponse) ProtoMessage()    {}

type DeleteNamespaceRequest struct {
	NamespaceName    *string `protobuf:"bytes,1,req,name=namespaceName" json:"namespaceName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteNamespaceRequest) Reset()         { *m = DeleteNamespaceRequest{} }
func (m *DeleteNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceRequest) ProtoMessage()    {}

func (m *DeleteNamespaceRequest) GetNamespaceName() string {
	if m != nil && m.NamespaceName != nil {
		return *m.NamespaceName
	}
	return ""
}

type DeleteNamespaceResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteNamespaceResponse) Reset()         { *m = DeleteNamespaceResponse{} }
func (m *DeleteNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceResponse) ProtoMessage()    {}

type ModifyNamespaceRequest struct {
	NamespaceDescriptor *NamespaceDescriptor `protobuf:"bytes,1,req,name=namespaceDescriptor" json:"namespaceDescriptor,omitempty"`
	XXX_unrecognized    []byte               `json:"-"`
}

func (m *ModifyNamespaceRequest) Reset()         { *m = ModifyNamespaceRequest{} }
func (m *ModifyNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyNamespaceRequest) ProtoMessage()    {}

func (m *ModifyNamespaceRequest) GetNamespaceDescriptor() *NamespaceDescriptor {
	if m != nil {
		return m.NamespaceDescriptor
	}
	return nil
}

type ModifyNamespaceResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ModifyNamespaceResponse) Reset()         { *m = ModifyNamespaceResponse{} }
func (m *ModifyNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyNamespaceResponse) ProtoMessage()    {}

type GetNamespaceDescriptorRequest struct {
	NamespaceName    *string `protobuf:"bytes,1,req,name=namespaceName" json:"namespaceName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetNamespaceDescriptorRequest) Reset()         { *m = GetNamespaceDescriptorRequest{} }
func (m *GetNamespaceDescriptorRequest) String() string { return proto.CompactTextString(m) }
func (*GetNamespaceDescriptorRequest) ProtoMessage()    {}

func (m *GetNamespaceDescriptorRequest) GetNamespaceName() string {
	if m != nil && m.NamespaceName != nil {
		return *m.NamespaceName
	}
	return ""
}

type GetNamespaceDescriptorResponse struct {
	NamespaceDescriptor *NamespaceDescriptor `protobuf:"bytes,1,req,name=namespaceDescriptor" json:"namespaceDescriptor,omitempty"`
	XXX_unrecognized    []byte               `json:"-"`
}

func (m *GetNamespaceDescriptorResponse) Reset()         { *m = GetNamespaceDescriptorResponse{} }
func (m *GetNamespaceDescriptorResponse) String() string { return proto.CompactTextString(m) }
func (*GetNamespaceDescriptorResponse) ProtoMessage()    {}

func (m *GetNamespaceDescriptorResponse) GetNamespaceDescriptor() *NamespaceDescriptor {
	if m != nil {
		return m.NamespaceDescriptor
	}
	return nil
}

type ListNamespaceDescriptorsRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ListNamespaceDescriptorsRequest) Reset()         { *m = ListNamespaceDescriptorsRequest{} }
func (m *ListNamespaceDescriptorsRequest) String() string { return proto.CompactTextString(m) }
func (*ListNamespaceDescriptorsRequest) ProtoMessage()    {}

type ListNamespaceDescriptorsResponse struct {
	NamespaceDescriptor []*NamespaceDescriptor `protobuf:"bytes,1,rep,name=namespaceDescriptor" json:"namespaceDescriptor,omitempty"`
	XXX_unrecognized    []byte                 `json:"-"`
}

func (m *ListNamespaceDescriptorsResponse) Reset()         { *m = ListNamespaceDescriptorsResponse{} }
func (m *ListNamespaceDescriptorsResponse) String() string { return proto.CompactTextString(m) }
func (*ListNamespaceDescriptorsResponse) ProtoMessage()    {}

func (m *ListNamespaceDescriptorsResponse) GetNamespaceDescriptor() []*NamespaceDescriptor {
	if m != nil {
		return m.NamespaceDescriptor
	}
	return nil
}

type ListTableDescriptorsByNamespaceRequest struct {
	NamespaceName    *string `protobuf:"bytes,1,req,name=namespaceName" json:"namespaceName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ListTableDescriptorsByNamespaceRequest) Reset() {
	*m = ListTableDescriptorsByNamespaceRequest{}
}
func (m *ListTableDescriptorsByNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*ListTableDescriptorsByNamespaceRequest) ProtoMessage()    {}

func (m *ListTableDescriptorsByNamespaceRequest) GetNamespaceName() string {
	if m != nil && m.NamespaceName != nil {
		return *m.NamespaceName
	}
	return ""
}

type ListTableDescriptorsByNamespaceResponse struct {
	TableSchema      []*TableSchema `protobuf:"bytes,1,rep,name=tableSchema" json:"tableSchema,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ListTableDescriptorsByNamespaceResponse) Reset() {
	*m = ListTableDescriptorsByNamespaceResponse{}
}
func (m *ListTableDescriptorsByNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*ListTableDescriptorsByNamespaceResponse) ProtoMessage()    {}

func (m *ListTableDescriptorsByNamespaceResponse) GetTableSchema() []*TableSchema {
	if m != nil {
		return m.TableSchema
	}
	return nil
}

type ListTableNamesByNamespaceRequest struct {
	NamespaceName    *string `protobuf:"bytes,1,req,name=namespaceName" json:"namespaceName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ListTableNamesByNamespaceRequest) Reset()         { *m = ListTableNamesByNamespaceRequest{} }
func (m *ListTableNamesByNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*ListTableNamesByNamespaceRequest) ProtoMessage()    {}

func (m *ListTableNamesByNamespaceRequest) GetNamespaceName() string {
	if m != nil && m.NamespaceName != nil {
		return *m.NamespaceName
	}
	return ""
}

type ListTableNamesByNamespaceResponse struct {
	TableName        []*TableName `protobuf:"bytes,1,rep,name=tableName" json:"tableName,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ListTableNamesByNamespaceResponse) Reset()         { *m = ListTableNamesByNamespaceResponse{} }
func (m *ListTableNamesByNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*ListTableNamesByNamespaceResponse) ProtoMessage()    {}

func (m *ListTableNamesByNamespaceResponse) GetTableName() []*TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

type ShutdownRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}

type ShutdownResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ShutdownResponse) Reset()         { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()    {}

type StopMasterRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StopMasterRequest) Reset()         { *m = StopMasterRequest{} }
func (m *StopMasterRequest) String() string { return proto.CompactTextString(m) }
func (*StopMasterRequest) ProtoMessage()    {}

type StopMasterResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StopMasterResponse) Reset()         { *m = StopMasterResponse{} }
func (m *StopMasterResponse) String() string { return proto.CompactTextString(m) }
func (*StopMasterResponse) ProtoMessage()    {}

type BalanceRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}

type BalanceResponse struct {
	BalancerRan      *bool  `protobuf:"varint,1,req,name=balancer_ran" json:"balancer_ran,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}

func (m *BalanceResponse) GetBalancerRan() bool {
	if m != nil && m.BalancerRan != nil {
		return *m.BalancerRan
	}
	return false
}

type SetBalancerRunningRequest struct {
	On               *bool  `protobuf:"varint,1,req,name=on" json:"on,omitempty"`
	Synchronous      *bool  `protobuf:"varint,2,opt,name=synchronous" json:"synchronous,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetBalancerRunningRequest) Reset()         { *m = SetBalancerRunningRequest{} }
func (m *SetBalancerRunningRequest) String() string { return proto.CompactTextString(m) }
func (*SetBalancerRunningRequest) ProtoMessage()    {}

func (m *SetBalancerRunningRequest) GetOn() bool {
	if m != nil && m.On != nil {
		return *m.On
	}
	return false
}

func (m *SetBalancerRunningRequest) GetSynchronous() bool {
	if m != nil && m.Synchronous != nil {
		return *m.Synchronous
	}
	return false
}

type SetBalancerRunningResponse struct {
	PrevBalanceValue *bool  `protobuf:"varint,1,opt,name=prev_balance_value" json:"prev_balance_value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetBalancerRunningResponse) Reset()         { *m = SetBalancerRunningResponse{} }
func (m *SetBalancerRunningResponse) String() string { return proto.CompactTextString(m) }
func (*SetBalancerRunningResponse) ProtoMessage()    {}

func (m *SetBalancerRunningResponse) GetPrevBalanceValue() bool {
	if m != nil && m.PrevBalanceValue != nil {
		return *m.PrevBalanceValue
	}
	return false
}

type IsBalancerEnabledRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IsBalancerEnabledRequest) Reset()         { *m = IsBalancerEnabledRequest{} }
func (m *IsBalancerEnabledRequest) String() string { return proto.CompactTextString(m) }
func (*IsBalancerEnabledRequest) ProtoMessage()    {}

type IsBalancerEnabledResponse struct {
	Enabled          *bool  `protobuf:"varint,1,req,name=enabled" json:"enabled,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IsBalancerEnabledResponse) Reset()         { *m = IsBalancerEnabledResponse{} }
func (m *IsBalancerEnabledResponse) String() string { return proto.CompactTextString(m) }
func (*IsBalancerEnabledResponse) ProtoMessage()    {}

func (m *IsBalancerEnabledResponse) GetEnabled() bool {
	if m != nil && m.Enabled != nil {
		return *m.Enabled
	}
	return false
}

type RunCatalogScanRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RunCatalogScanRequest) Reset()         { *m = RunCatalogScanRequest{} }
func (m *RunCatalogScanRequest) String() string { return proto.CompactTextString(m) }
func (*RunCatalogScanRequest) ProtoMessage()    {}

type RunCatalogScanResponse struct {
	ScanResult       *int32 `protobuf:"varint,1,opt,name=scan_result" json:"scan_result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RunCatalogScanResponse) Reset()         { *m = RunCatalogScanResponse{} }
func (m *RunCatalogScanResponse) String() string { return proto.CompactTextString(m) }
func (*RunCatalogScanResponse) ProtoMessage()    {}

func (m *RunCatalogScanResponse) GetScanResult() int32 {
	if m != nil && m.ScanResult != nil {
		return *m.ScanResult
	}
	return 0
}

type EnableCatalogJanitorRequest struct {
	Enable           *bool  `protobuf:"varint,1,req,name=enable" json:"enable,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EnableCatalogJanitorRequest) Reset()         { *m = EnableCatalogJanitorRequest{} }
func (m *EnableCatalogJanitorRequest) String() string { return proto.CompactTextString(m) }
func (*EnableCatalogJanitorRequest) ProtoMessage()    {}

func (m *EnableCatalogJanitorRequest) GetEnable() bool {
	if m != nil && m.Enable != nil {
		return *m.Enable
	}
	return false
}

type EnableCatalogJanitorResponse struct {
	PrevValue        *bool  `protobuf:"varint,1,opt,name=prev_value" json:"prev_value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EnableCatalogJanitorResponse) Reset()         { *m = EnableCatalogJanitorResponse{} }
func (m *EnableCatalogJanitorResponse) String() string { return proto.CompactTextString(m) }
func (*EnableCatalogJanitorResponse) ProtoMessage()    {}

func (m *EnableCatalogJanitorResponse) GetPrevValue() bool {
	if m != nil && m.PrevValue != nil {
		return *m.PrevValue
	}
	return false
}

type IsCatalogJanitorEnabledRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IsCatalogJanitorEnabledRequest) Reset()         { *m = IsCatalogJanitorEnabledRequest{} }
func (m *IsCatalogJanitorEnabledRequest) String() string { return proto.CompactTextString(m) }
func (*IsCatalogJanitorEnabledRequest) ProtoMessage()    {}

type IsCatalogJanitorEnabledResponse struct {
	Value            *bool  `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IsCatalogJanitorEnabledResponse) Reset()         { *m = IsCatalogJanitorEnabledResponse{} }
func (m *IsCatalogJanitorEnabledResponse) String() string { return proto.CompactTextString(m) }
func (*IsCatalogJanitorEnabledResponse) ProtoMessage()    {}

func (m *IsCatalogJanitorEnabledResponse) GetValue() bool {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return false
}

type SnapshotRequest struct {
	Snapshot         *SnapshotDescription `protobuf:"bytes,1,req,name=snapshot" json:"snapshot,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *SnapshotRequest) Reset()         { *m = SnapshotRequest{} }
func (m *SnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*SnapshotRequest) ProtoMessage()    {}

func (m *SnapshotRequest) GetSnapshot() *SnapshotDescription {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type SnapshotResponse struct {
	ExpectedTimeout  *int64 `protobuf:"varint,1,req,name=expected_timeout" json:"expected_timeout,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SnapshotResponse) Reset()         { *m = SnapshotResponse{} }
func (m *SnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*SnapshotResponse) ProtoMessage()    {}

func (m *SnapshotResponse) GetExpectedTimeout() int64 {
	if m != nil && m.ExpectedTimeout != nil {
		return *m.ExpectedTimeout
	}
	return 0
}

type GetCompletedSnapshotsRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetCompletedSnapshotsRequest) Reset()         { *m = GetCompletedSnapshotsRequest{} }
func (m *GetCompletedSnapshotsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCompletedSnapshotsRequest) ProtoMessage()    {}

type GetCompletedSnapshotsResponse struct {
	Snapshots        []*SnapshotDescription `protobuf:"bytes,1,rep,name=snapshots" json:"snapshots,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *GetCompletedSnapshotsResponse) Reset()         { *m = GetCompletedSnapshotsResponse{} }
func (m *GetCompletedSnapshotsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCompletedSnapshotsResponse) ProtoMessage()    {}

func (m *GetCompletedSnapshotsResponse) GetSnapshots() []*SnapshotDescription {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

type DeleteSnapshotRequest struct {
	Snapshot         *SnapshotDescription `protobuf:"bytes,1,req,name=snapshot" json:"snapshot,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *DeleteSnapshotRequest) Reset()         { *m = DeleteSnapshotRequest{} }
func (m *DeleteSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSnapshotRequest) ProtoMessage()    {}

func (m *DeleteSnapshotRequest) GetSnapshot() *SnapshotDescription {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type DeleteSnapshotResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteSnapshotResponse) Reset()         { *m = DeleteSnapshotResponse{} }
func (m *DeleteSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSnapshotResponse) ProtoMessage()    {}

type RestoreSnapshotRequest struct {
	Snapshot         *SnapshotDescription `protobuf:"bytes,1,req,name=snapshot" json:"snapshot,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *RestoreSnapshotRequest) Reset()         { *m = RestoreSnapshotRequest{} }
func (m *RestoreSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreSnapshotRequest) ProtoMessage()    {}

func (m *RestoreSnapshotRequest) GetSnapshot() *SnapshotDescription {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type RestoreSnapshotResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RestoreSnapshotResponse) Reset()         { *m = RestoreSnapshotResponse{} }
func (m *RestoreSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreSnapshotResponse) ProtoMessage()    {}

// if you don't send the snapshot, then you will get it back
// in the response (if the snapshot is done) so you can check the snapshot
type IsSnapshotDoneRequest struct {
	Snapshot         *SnapshotDescription `protobuf:"bytes,1,opt,name=snapshot" json:"snapshot,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *IsSnapshotDoneRequest) Reset()         { *m = IsSnapshotDoneRequest{} }
func (m *IsSnapshotDoneRequest) String() string { return proto.CompactTextString(m) }
func (*IsSnapshotDoneRequest) ProtoMessage()    {}

func (m *IsSnapshotDoneRequest) GetSnapshot() *SnapshotDescription {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type IsSnapshotDoneResponse struct {
	Done             *bool                `protobuf:"varint,1,opt,name=done,def=0" json:"done,omitempty"`
	Snapshot         *SnapshotDescription `protobuf:"bytes,2,opt,name=snapshot" json:"snapshot,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *IsSnapshotDoneResponse) Reset()         { *m = IsSnapshotDoneResponse{} }
func (m *IsSnapshotDoneResponse) String() string { return proto.CompactTextString(m) }
func (*IsSnapshotDoneResponse) ProtoMessage()    {}

const Default_IsSnapshotDoneResponse_Done bool = false

func (m *IsSnapshotDoneResponse) GetDone() bool {
	if m != nil && m.Done != nil {
		return *m.Done
	}
	return Default_IsSnapshotDoneResponse_Done
}

func (m *IsSnapshotDoneResponse) GetSnapshot() *SnapshotDescription {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type IsRestoreSnapshotDoneRequest struct {
	Snapshot         *SnapshotDescription `protobuf:"bytes,1,opt,name=snapshot" json:"snapshot,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *IsRestoreSnapshotDoneRequest) Reset()         { *m = IsRestoreSnapshotDoneRequest{} }
func (m *IsRestoreSnapshotDoneRequest) String() string { return proto.CompactTextString(m) }
func (*IsRestoreSnapshotDoneRequest) ProtoMessage()    {}

func (m *IsRestoreSnapshotDoneRequest) GetSnapshot() *SnapshotDescription {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type IsRestoreSnapshotDoneResponse struct {
	Done             *bool  `protobuf:"varint,1,opt,name=done,def=0" json:"done,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IsRestoreSnapshotDoneResponse) Reset()         { *m = IsRestoreSnapshotDoneResponse{} }
func (m *IsRestoreSnapshotDoneResponse) String() string { return proto.CompactTextString(m) }
func (*IsRestoreSnapshotDoneResponse) ProtoMessage()    {}

const Default_IsRestoreSnapshotDoneResponse_Done bool = false

func (m *IsRestoreSnapshotDoneResponse) GetDone() bool {
	if m != nil && m.Done != nil {
		return *m.Done
	}
	return Default_IsRestoreSnapshotDoneResponse_Done
}

type GetSchemaAlterStatusRequest struct {
	TableName        *TableName `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *GetSchemaAlterStatusRequest) Reset()         { *m = GetSchemaAlterStatusRequest{} }
func (m *GetSchemaAlterStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetSchemaAlterStatusRequest) ProtoMessage()    {}

func (m *GetSchemaAlterStatusRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

type GetSchemaAlterStatusResponse struct {
	YetToUpdateRegions *uint32 `protobuf:"varint,1,opt,name=yet_to_update_regions" json:"yet_to_update_regions,omitempty"`
	TotalRegions       *uint32 `protobuf:"varint,2,opt,name=total_regions" json:"total_regions,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *GetSchemaAlterStatusResponse) Reset()         { *m = GetSchemaAlterStatusResponse{} }
func (m *GetSchemaAlterStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetSchemaAlterStatusResponse) ProtoMessage()    {}

func (m *GetSchemaAlterStatusResponse) GetYetToUpdateRegions() uint32 {
	if m != nil && m.YetToUpdateRegions != nil {
		return *m.YetToUpdateRegions
	}
	return 0
}

func (m *GetSchemaAlterStatusResponse) GetTotalRegions() uint32 {
	if m != nil && m.TotalRegions != nil {
		return *m.TotalRegions
	}
	return 0
}

type GetTableDescriptorsRequest struct {
	TableNames       []*TableName `protobuf:"bytes,1,rep,name=table_names" json:"table_names,omitempty"`
	Regex            *string      `protobuf:"bytes,2,opt,name=regex" json:"regex,omitempty"`
	IncludeSysTables *bool        `protobuf:"varint,3,opt,name=include_sys_tables,def=0" json:"include_sys_tables,omitempty"`
	Namespace        *string      `protobuf:"bytes,4,opt,name=namespace" json:"namespace,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetTableDescriptorsRequest) Reset()         { *m = GetTableDescriptorsRequest{} }
func (m *GetTableDescriptorsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTableDescriptorsRequest) ProtoMessage()    {}

const Default_GetTableDescriptorsRequest_IncludeSysTables bool = false

func (m *GetTableDescriptorsRequest) GetTableNames() []*TableName {
	if m != nil {
		return m.TableNames
	}
	return nil
}

func (m *GetTableDescriptorsRequest) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

func (m *GetTableDescriptorsRequest) GetIncludeSysTables() bool {
	if m != nil && m.IncludeSysTables != nil {
		return *m.IncludeSysTables
	}
	return Default_GetTableDescriptorsRequest_IncludeSysTables
}

func (m *GetTableDescriptorsRequest) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

type GetTableDescriptorsResponse struct {
	TableSchema      []*TableSchema `protobuf:"bytes,1,rep,name=table_schema" json:"table_schema,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetTableDescriptorsResponse) Reset()         { *m = GetTableDescriptorsResponse{} }
func (m *GetTableDescriptorsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTableDescriptorsResponse) ProtoMessage()    {}

func (m *GetTableDescriptorsResponse) GetTableSchema() []*TableSchema {
	if m != nil {
		return m.TableSchema
	}
	return nil
}

type GetTableNamesRequest struct {
	Regex            *string `protobuf:"bytes,1,opt,name=regex" json:"regex,omitempty"`
	IncludeSysTables *bool   `protobuf:"varint,2,opt,name=include_sys_tables,def=0" json:"include_sys_tables,omitempty"`
	Namespace        *string `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetTableNamesRequest) Reset()         { *m = GetTableNamesRequest{} }
func (m *GetTableNamesRequest) String() string { return proto.CompactTextString(m) }
func (*GetTableNamesRequest) ProtoMessage()    {}

const Default_GetTableNamesRequest_IncludeSysTables bool = false

func (m *GetTableNamesRequest) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

func (m *GetTableNamesRequest) GetIncludeSysTables() bool {
	if m != nil && m.IncludeSysTables != nil {
		return *m.IncludeSysTables
	}
	return Default_GetTableNamesRequest_IncludeSysTables
}

func (m *GetTableNamesRequest) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

type GetTableNamesResponse struct {
	TableNames       []*TableName `protobuf:"bytes,1,rep,name=table_names" json:"table_names,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetTableNamesResponse) Reset()         { *m = GetTableNamesResponse{} }
func (m *GetTableNamesResponse) String() string { return proto.CompactTextString(m) }
func (*GetTableNamesResponse) ProtoMessage()    {}

func (m *GetTableNamesResponse) GetTableNames() []*TableName {
	if m != nil {
		return m.TableNames
	}
	return nil
}

type GetClusterStatusRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetClusterStatusRequest) Reset()         { *m = GetClusterStatusRequest{} }
func (m *GetClusterStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterStatusRequest) ProtoMessage()    {}

type GetClusterStatusResponse struct {
	ClusterStatus    *ClusterStatus `protobuf:"bytes,1,req,name=cluster_status" json:"cluster_status,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetClusterStatusResponse) Reset()         { *m = GetClusterStatusResponse{} }
func (m *GetClusterStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterStatusResponse) ProtoMessage()    {}

func (m *GetClusterStatusResponse) GetClusterStatus() *ClusterStatus {
	if m != nil {
		return m.ClusterStatus
	}
	return nil
}

type IsMasterRunningRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IsMasterRunningRequest) Reset()         { *m = IsMasterRunningRequest{} }
func (m *IsMasterRunningRequest) String() string { return proto.CompactTextString(m) }
func (*IsMasterRunningRequest) ProtoMessage()    {}

type IsMasterRunningResponse struct {
	IsMasterRunning  *bool  `protobuf:"varint,1,req,name=is_master_running" json:"is_master_running,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IsMasterRunningResponse) Reset()         { *m = IsMasterRunningResponse{} }
func (m *IsMasterRunningResponse) String() string { return proto.CompactTextString(m) }
func (*IsMasterRunningResponse) ProtoMessage()    {}

func (m *IsMasterRunningResponse) GetIsMasterRunning() bool {
	if m != nil && m.IsMasterRunning != nil {
		return *m.IsMasterRunning
	}
	return false
}

type ExecProcedureRequest struct {
	Procedure        *ProcedureDescription `protobuf:"bytes,1,req,name=procedure" json:"procedure,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ExecProcedureRequest) Reset()         { *m = ExecProcedureRequest{} }
func (m *ExecProcedureRequest) String() string { return proto.CompactTextString(m) }
func (*ExecProcedureRequest) ProtoMessage()    {}

func (m *ExecProcedureRequest) GetProcedure() *ProcedureDescription {
	if m != nil {
		return m.Procedure
	}
	return nil
}

type ExecProcedureResponse struct {
	ExpectedTimeout  *int64 `protobuf:"varint,1,opt,name=expected_timeout" json:"expected_timeout,omitempty"`
	ReturnData       []byte `protobuf:"bytes,2,opt,name=return_data" json:"return_data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ExecProcedureResponse) Reset()         { *m = ExecProcedureResponse{} }
func (m *ExecProcedureResponse) String() string { return proto.CompactTextString(m) }
func (*ExecProcedureResponse) ProtoMessage()    {}

func (m *ExecProcedureResponse) GetExpectedTimeout() int64 {
	if m != nil && m.ExpectedTimeout != nil {
		return *m.ExpectedTimeout
	}
	return 0
}

func (m *ExecProcedureResponse) GetReturnData() []byte {
	if m != nil {
		return m.ReturnData
	}
	return nil
}

type IsProcedureDoneRequest struct {
	Procedure        *ProcedureDescription `protobuf:"bytes,1,opt,name=procedure" json:"procedure,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *IsProcedureDoneRequest) Reset()         { *m = IsProcedureDoneRequest{} }
func (m *IsProcedureDoneRequest) String() string { return proto.CompactTextString(m) }
func (*IsProcedureDoneRequest) ProtoMessage()    {}

func (m *IsProcedureDoneRequest) GetProcedure() *ProcedureDescription {
	if m != nil {
		return m.Procedure
	}
	return nil
}

type IsProcedureDoneResponse struct {
	Done             *bool                 `protobuf:"varint,1,opt,name=done,def=0" json:"done,omitempty"`
	Snapshot         *ProcedureDescription `protobuf:"bytes,2,opt,name=snapshot" json:"snapshot,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *IsProcedureDoneResponse) Reset()         { *m = IsProcedureDoneResponse{} }
func (m *IsProcedureDoneResponse) String() string { return proto.CompactTextString(m) }
func (*IsProcedureDoneResponse) ProtoMessage()    {}

const Default_IsProcedureDoneResponse_Done bool = false

func (m *IsProcedureDoneResponse) GetDone() bool {
	if m != nil && m.Done != nil {
		return *m.Done
	}
	return Default_IsProcedureDoneResponse_Done
}

func (m *IsProcedureDoneResponse) GetSnapshot() *ProcedureDescription {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type GetProcedureResultRequest struct {
	ProcId           *uint64 `protobuf:"varint,1,req,name=proc_id" json:"proc_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetProcedureResultRequest) Reset()         { *m = GetProcedureResultRequest{} }
func (m *GetProcedureResultRequest) String() string { return proto.CompactTextString(m) }
func (*GetProcedureResultRequest) ProtoMessage()    {}

func (m *GetProcedureResultRequest) GetProcId() uint64 {
	if m != nil && m.ProcId != nil {
		return *m.ProcId
	}
	return 0
}

type GetProcedureResultResponse struct {
	State            *GetProcedureResultResponse_State `protobuf:"varint,1,req,name=state,enum=pb.GetProcedureResultResponse_State" json:"state,omitempty"`
	StartTime        *uint64                           `protobuf:"varint,2,opt,name=start_time" json:"start_time,omitempty"`
	LastUpdate       *uint64                           `protobuf:"varint,3,opt,name=last_update" json:"last_update,omitempty"`
	Result           []byte                            `protobuf:"bytes,4,opt,name=result" json:"result,omitempty"`
	Exception        *ForeignExceptionMessage          `protobuf:"bytes,5,opt,name=exception" json:"exception,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *GetProcedureResultResponse) Reset()         { *m = GetProcedureResultResponse{} }
func (m *GetProcedureResultResponse) String() string { return proto.CompactTextString(m) }
func (*GetProcedureResultResponse) ProtoMessage()    {}

func (m *GetProcedureResultResponse) GetState() GetProcedureResultResponse_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return GetProcedureResultResponse_NOT_FOUND
}

func (m *GetProcedureResultResponse) GetStartTime() uint64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *GetProcedureResultResponse) GetLastUpdate() uint64 {
	if m != nil && m.LastUpdate != nil {
		return *m.LastUpdate
	}
	return 0
}

func (m *GetProcedureResultResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetProcedureResultResponse) GetException() *ForeignExceptionMessage {
	if m != nil {
		return m.Exception
	}
	return nil
}

type SetQuotaRequest struct {
	UserName         *string          `protobuf:"bytes,1,opt,name=user_name" json:"user_name,omitempty"`
	UserGroup        *string          `protobuf:"bytes,2,opt,name=user_group" json:"user_group,omitempty"`
	Namespace        *string          `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	TableName        *TableName       `protobuf:"bytes,4,opt,name=table_name" json:"table_name,omitempty"`
	RemoveAll        *bool            `protobuf:"varint,5,opt,name=remove_all" json:"remove_all,omitempty"`
	BypassGlobals    *bool            `protobuf:"varint,6,opt,name=bypass_globals" json:"bypass_globals,omitempty"`
	Throttle         *ThrottleRequest `protobuf:"bytes,7,opt,name=throttle" json:"throttle,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SetQuotaRequest) Reset()         { *m = SetQuotaRequest{} }
func (m *SetQuotaRequest) String() string { return proto.CompactTextString(m) }
func (*SetQuotaRequest) ProtoMessage()    {}

func (m *SetQuotaRequest) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *SetQuotaRequest) GetUserGroup() string {
	if m != nil && m.UserGroup != nil {
		return *m.UserGroup
	}
	return ""
}

func (m *SetQuotaRequest) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

func (m *SetQuotaRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *SetQuotaRequest) GetRemoveAll() bool {
	if m != nil && m.RemoveAll != nil {
		return *m.RemoveAll
	}
	return false
}

func (m *SetQuotaRequest) GetBypassGlobals() bool {
	if m != nil && m.BypassGlobals != nil {
		return *m.BypassGlobals
	}
	return false
}

func (m *SetQuotaRequest) GetThrottle() *ThrottleRequest {
	if m != nil {
		return m.Throttle
	}
	return nil
}

type SetQuotaResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetQuotaResponse) Reset()         { *m = SetQuotaResponse{} }
func (m *SetQuotaResponse) String() string { return proto.CompactTextString(m) }
func (*SetQuotaResponse) ProtoMessage()    {}

type MajorCompactionTimestampRequest struct {
	TableName        *TableName `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MajorCompactionTimestampRequest) Reset()         { *m = MajorCompactionTimestampRequest{} }
func (m *MajorCompactionTimestampRequest) String() string { return proto.CompactTextString(m) }
func (*MajorCompactionTimestampRequest) ProtoMessage()    {}

func (m *MajorCompactionTimestampRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

type MajorCompactionTimestampForRegionRequest struct {
	Region           *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MajorCompactionTimestampForRegionRequest) Reset() {
	*m = MajorCompactionTimestampForRegionRequest{}
}
func (m *MajorCompactionTimestampForRegionRequest) String() string { return proto.CompactTextString(m) }
func (*MajorCompactionTimestampForRegionRequest) ProtoMessage()    {}

func (m *MajorCompactionTimestampForRegionRequest) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

type MajorCompactionTimestampResponse struct {
	CompactionTimestamp *int64 `protobuf:"varint,1,req,name=compaction_timestamp" json:"compaction_timestamp,omitempty"`
	XXX_unrecognized    []byte `json:"-"`
}

func (m *MajorCompactionTimestampResponse) Reset()         { *m = MajorCompactionTimestampResponse{} }
func (m *MajorCompactionTimestampResponse) String() string { return proto.CompactTextString(m) }
func (*MajorCompactionTimestampResponse) ProtoMessage()    {}

func (m *MajorCompactionTimestampResponse) GetCompactionTimestamp() int64 {
	if m != nil && m.CompactionTimestamp != nil {
		return *m.CompactionTimestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.GetProcedureResultResponse_State", GetProcedureResultResponse_State_name, GetProcedureResultResponse_State_value)
}
